version: '3.9'

services:
  web:
    build: .
    container_name: chat_web
    command: bash -c "python manage.py migrate --noinput && daphne -b 0.0.0.0 -p 8000 chat_room.asgi:application"
    ports:
      - "8000:8000"

    depends_on:
      - redis
    environment:
      - DEBUG=True
      - SECRET_KEY=vt259124$c3d^6%g2i9dct%=-v4mn0==($3%xfv0i%nvk^(^yh
      - DATABASE_URL=postgres://postgres:WhEWYYaQMs13FzfBDrT0@chat-room.chyssao6a5ch.ap-south-1.rds.amazonaws.com/chat_db
      - REDIS_URL=redis://redis:6379


  redis:
    image: redis:7
    container_name: chat_redis
    ports:
      - "6379:6379"



