services:
  - type: web
    name: live-chat-room
    env: python
    buildCommand: "./manage.py collectstatic --noinput"
    startCommand: ./start.sh
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: chat_room.settings
      - key: PORT
        value: 10000
