# Generated by Django 5.1.5 on 2025-02-18 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_room_options_room_topics"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="topic",
        ),
    ]
