# Generated by Django 5.1.5 on 2025-03-18 13:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_membership_room_participants_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["-updated", "-created"]},
        ),
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ["updated", "created"]},
        ),
        migrations.AlterField(
            model_name="room",
            name="participants",
            field=models.ManyToManyField(
                related_name="joined_rooms",
                through="main.Membership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
