# Generated by Django 5.1.5 on 2025-03-18 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_alter_room_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={},
        ),
    ]
