# Generated by Django 5.1.5 on 2025-03-19 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_alter_message_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={},
        ),
    ]
