# Generated by Django 5.1.5 on 2025-03-19 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_alter_room_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ["-updated", "-created"]},
        ),
    ]
